branches:
  only:
  - preprod
  
language: node_js
node_js:
  - 12

services:
  - docker

before_script:
  - touch .env
  - touch ./config/env.json
  - node ./scripts/setupTestEnv.js
  - docker build -t aquilacms/aquilacms .
  - docker pull mongo

script:
  - docker network create aquila
  - docker run -d --name mongo -p 27017:27017 --network=aquila mongo
  - docker exec -i mongo sh -c 'mongorestore --archive --drop' < ./test/data/test/archive
  - docker run -d --name aquilacms -p 127.0.0.1:3050:3050/tcp --network=aquila aquilacms/aquilacms
  - docker exec -i -e PORT=3051 aquilacms npm run test